In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Dados-modelo/df_preliminar.csv', sep=';')

In [ ]:
display(
    df.info(),
    df.describe(),
    df.isna().sum()
    )

In [ ]:
# Correlacao 1
cols = [
    'TEMPO',
    'DISTANCIA',
    'INCID_MEDIA_GERAL',
    'PROP_MG',
    'PROP_POP_0A10',
    'PROP_POP_60MAIS'
]

df[cols].corr().round(2)

,TEMPO,DISTANCIA,INCID_MEDIA_GERAL,PROP_MG,PROP_POP_0A10,PROP_POP_60MAIS
TEMPO,1.00,0.98,0.08,-0.14,-0.04,0.15
DISTANCIA,0.98,1.00,0.09,-0.13,-0.05,0.16
INCID_MEDIA_GERAL,0.08,0.09,1.00,-0.19,-0.32,0.34
PROP_MG,-0.14,-0.13,-0.19,1.00,0.17,-0.13
PROP_POP_0A10,-0.04,-0.05,-0.32,0.17,1.00,-0.69
PROP_POP_60MAIS,0.15,0.16,0.34,-0.13,-0.69,1.00

In [14]:
# Listar extremos

display(
df.nlargest(20, 'PROP_MG')['MUNI_REFERENCIADO'],

df.nlargest(20, 'TEMPO')['MUNI_REFERENCIADO'],

df.nlargest(20, 'INCID_MEDIA_GERAL')['MUNI_REFERENCIADO']
)

164                  NOVA CAMPINA
535                   JACUPIRANGA
540                   SETE BARRAS
592                         APIAI
549                      BERTIOGA
294                       SERRANA
121                        TAGUAI
299           RIO GRANDE DA SERRA
306                  DIVINOLANDIA
543                        CAJURU
584                      ANGATUBA
555                  PRAIA GRANDE
586                  ITAPETININGA
79                        BOCAINA
453    SANTO ANTONIO DO ARACANGUA
571                       UBATUBA
501                    PEDREGULHO
112                    ITAPORANGA
160        SAO JOSE DA BELA VISTA
66                        GUARACI
Name: MUNI_REFERENCIADO, dtype: str

141                  PIRACAIA
392       NATIVIDADE DA SERRA
117                 PORANGABA
429                 UBIRAJARA
328                    IRAPUA
162    BOM SUCESSO DE ITARARE
165                   RIBEIRA
123            TORRE DE PEDRA
344            PAULO DE FARIA
67                  JABORANDI
63                    TIMBURI
326            GASTAO VIDIGAL
101                       URU
421                  GUARANTA
330                  MACAUBAL
103                   ANHEMBI
31                    DOURADO
166                  RIVERSUL
415     CAMPOS NOVOS PAULISTA
417                    FERNAO
Name: MUNI_REFERENCIADO, dtype: str

174                  INDIAPORA
15            MURUTINGA DO SUL
246       SANTA MARIA DA SERRA
447                   GUARACAI
270              MONTE CASTELO
632              MIRASSOLANDIA
641                 ONDA VERDE
315           ALVARES FLORENCE
179               MIRA ESTRELA
582                   OUROESTE
340                  PALESTINA
2                      BARBOSA
520    MIRANTE DO PARANAPANEMA
450               MIRANDOPOLIS
273                  PAULICEIA
343                     PARISI
183               PEDRANOPOLIS
271          NOVA GUATAPORANGA
17          NOVA INDEPENDENCIA
633                POTIRENDABA
Name: MUNI_REFERENCIADO, dtype: str

In [16]:
# Correlação 2
cols = [
    'TEMPO',
    'DISTANCIA',
    'INCID_MEDIA_GERAL',
    'PROP_MG',
    'PROP_CASOS_0A10',
    'PROP_CASOS_60MAIS'
]

df[cols].corr().round(2)

,TEMPO,DISTANCIA,INCID_MEDIA_GERAL,PROP_MG,PROP_CASOS_0A10,PROP_CASOS_60MAIS
TEMPO,1.00,0.98,0.08,-0.14,0.04,0.04
DISTANCIA,0.98,1.00,0.09,-0.13,0.05,0.05
INCID_MEDIA_GERAL,0.08,0.09,1.00,-0.19,-0.09,0.32
PROP_MG,-0.14,-0.13,-0.19,1.00,0.28,-0.08
PROP_CASOS_0A10,0.04,0.05,-0.09,0.28,1.00,-0.18
PROP_CASOS_60MAIS,0.04,0.05,0.32,-0.08,-0.18,1.00

In [6]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'ACESSO_LOCAL', 'MULTIPLO_PESA', 'REGIAO',
       'PESA', 'MUNI_REFERENCIADO', 'OBSERVACOES', 'LAT_MUNI', 'LON_MUNI',
       'LAT_PESA', 'LON_PESA', 'DISTANCIA', 'TEMPO', 'IBGE', 'MUNI_NOME_x',
       'POP10', 'POP12', 'POP11A59', 'POP60', 'POP_GERAL', 'MACRO_CODIGO',
       'MACRO_NOME', 'DRS_CODIGO', 'DRS_NOME', 'CIR_CODIGO', 'CIR_NOME',
       'TOTAL_CASOS', 'TOTAL_10A', 'TOTAL_12A', 'TOTAL_11A59', 'TOTAL_60',
       'LEVE', 'MG', 'LEVE_10', 'MG_10', 'LEVE_12', 'MG_12', 'LEVE_11A59',
       'MG_11A59', 'LEVE_60', 'MG_60', 'TOTAL_AMPOLAS', 'CAT_TEMPO',
       'PROP_POP_0A10', 'PROP_POP_60MAIS', 'LOG_POP', 'PROP_MG',
       'INCID_MEDIA_GERAL', 'INCID_0A10', 'INCID_60MAIS', 'PROP_CASOS_0A10',
       'PROP_CASOS_60MAIS', 'TAXA_MG_100MIL', 'CLASS_IG', 'SORO_IG', 'EVOL_IG',
       'PROP_CLASS_IGN', 'PROP_SORO_IGN', 'PROP_EVOL_IGN', 'BAIXO_N'],
      dtype='str')