In [9]:
import pandas as pd
import numpy as np

In [10]:
casos_ibge = pd.read_excel('dados/ibge.xlsx')
sinan_mg2 = pd.read_csv('dados/sinan_mg2.csv', sep=';')
base01 = pd.read_excel('dados/base01.xlsx')

/tmp/ipykernel_20721/184929053.py:2: DtypeWarning: Columns (0: COM_RENAL, 1: COM_EDEMA, 2: COM_SEPTIC, 3: COM_CHOQUE, 4: DT_OBITO, 5: DT_DIGITA) have mixed types. Specify dtype option on import or set low_memory=False.
  sinan_mg2 = pd.read_csv('dados/sinan_mg2.csv', sep=';')

In [11]:
base01

,ACESSO_LOCAL,MULTIPLO_PESA,REGIAO,PESA,MUNI_REFERENCIADO,OBSERVACOES,LAT_MUNI,LON_MUNI,LAT_PESA,LON_PESA,DISTANCIA,TEMPO
0,0,0,ARACATUBA,PENAPOLIS,ALTO ALEGRE,TODOS,-21.582059,-50.166198,-21.416404,-50.064911,23.5,25.7
1,0,0,ARACATUBA,PENAPOLIS,AVANHANDAVA,TODOS,-21.460333,-49.946516,-21.416404,-50.064911,14.1,15.9
2,0,0,ARACATUBA,PENAPOLIS,BARBOSA,TODOS,-21.265661,-49.951816,-21.416404,-50.064911,26.7,22.8
3,0,0,ARACATUBA,VALPARAISO,BENTO DE ABREU,TODOS,-21.271572,-50.811723,-21.230655,-50.861195,9.5,12.8
4,0,0,ARACATUBA,CLEMENTINA,BILAC,TODOS,-21.403962,-50.474640,-21.556698,-50.446533,21.6,19.8
...,...,...,...,...,...,...,...,...,...,...,...,...
640,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,IPIGUA,TODOS,NaN,NaN,NaN,NaN,27.3,37.0
641,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,ONDA VERDE,TODOS,NaN,NaN,NaN,NaN,32.4,35.0
642,1,0,PIRACICABA,PIRACICABA,PIRACICABA,TODOS,NaN,NaN,NaN,NaN,0.0,0.0
643,0,0,PIRACICABA,PIRACICABA,RIO DAS PEDRAS,TODOS,NaN,NaN,NaN,NaN,16.4,22.0
644,1,0,CARAGUATATUBA,ILHABELA,ILHABELA,TODOS,NaN,NaN,NaN,NaN,0.0,0.0

In [12]:
# Merge Base02 e Sinan_agregado
df = base01.merge(
    left_on='MUNI_REFERENCIADO',
    right_on='MUNI',
    how='left',
    right=casos_ibge
)

In [13]:
df.isna().sum()
#df.columns

ACESSO_LOCAL          0
MULTIPLO_PESA         0
REGIAO                0
PESA                  0
MUNI_REFERENCIADO     0
OBSERVACOES           0
LAT_MUNI             28
LON_MUNI             28
LAT_PESA             28
LON_PESA             28
DISTANCIA             2
TEMPO                 2
Unnamed: 0            0
IBGE                  0
POP10                 0
POP11A59              0
POP60                 0
POP_GERAL             0
MUNI                  0
TOTAL_CASOS           7
TOTAL_10A            56
TOTAL_11A59           7
TOTAL_60             42
LEVE                  7
MG                    7
MG_ORIGINAL          64
LEVE_10              56
MG_10                56
LEVE_11A59            7
MG_11A59              7
LEVE_60              42
MG_60                42
TOTAL_AMPOLAS         7
dtype: int64

In [14]:
df

,ACESSO_LOCAL,MULTIPLO_PESA,REGIAO,PESA,MUNI_REFERENCIADO,OBSERVACOES,LAT_MUNI,LON_MUNI,LAT_PESA,LON_PESA,...,LEVE,MG,MG_ORIGINAL,LEVE_10,MG_10,LEVE_11A59,MG_11A59,LEVE_60,MG_60,TOTAL_AMPOLAS
0,0,0,ARACATUBA,PENAPOLIS,ALTO ALEGRE,TODOS,-21.582059,-50.166198,-21.416404,-50.064911,...,286.0,9.0,11.0,11.0,5.0,159.0,1.0,109.0,3.0,23.0
1,0,0,ARACATUBA,PENAPOLIS,AVANHANDAVA,TODOS,-21.460333,-49.946516,-21.416404,-50.064911,...,228.0,17.0,16.0,12.0,5.0,166.0,11.0,49.0,1.0,36.0
2,0,0,ARACATUBA,PENAPOLIS,BARBOSA,TODOS,-21.265661,-49.951816,-21.416404,-50.064911,...,444.0,10.0,14.0,40.0,8.0,309.0,2.0,91.0,0.0,38.0
3,0,0,ARACATUBA,VALPARAISO,BENTO DE ABREU,TODOS,-21.271572,-50.811723,-21.230655,-50.861195,...,79.0,4.0,3.0,8.0,1.0,57.0,1.0,14.0,2.0,21.0
4,0,0,ARACATUBA,CLEMENTINA,BILAC,TODOS,-21.403962,-50.474640,-21.556698,-50.446533,...,252.0,8.0,13.0,15.0,2.0,155.0,3.0,77.0,3.0,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,IPIGUA,TODOS,NaN,NaN,NaN,NaN,...,232.0,17.0,22.0,16.0,5.0,153.0,10.0,60.0,2.0,36.0
641,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,ONDA VERDE,TODOS,NaN,NaN,NaN,NaN,...,249.0,9.0,16.0,35.0,3.0,165.0,5.0,40.0,1.0,9.0
642,1,0,PIRACICABA,PIRACICABA,PIRACICABA,TODOS,NaN,NaN,NaN,NaN,...,7912.0,143.0,171.0,688.0,81.0,5926.0,46.0,1209.0,16.0,452.0
643,0,0,PIRACICABA,PIRACICABA,RIO DAS PEDRAS,TODOS,NaN,NaN,NaN,NaN,...,293.0,5.0,14.0,40.0,4.0,210.0,0.0,36.0,1.0,19.0
644,1,0,CARAGUATATUBA,ILHABELA,ILHABELA,TODOS,NaN,NaN,NaN,NaN,...,6.0,0.0,NaN,NaN,NaN,5.0,0.0,1.0,0.0,0.0

In [15]:
# Preenche com Zero os valores ausentes
df = df.fillna(0)

# Exclui colunas inuteis
df = df.drop(columns=['Unnamed: 0','MUNI'])

In [16]:
# Salvar base03
df.to_excel('dados/base_preliminar.xlsx')

Próxima etapa será calcular as taxas