In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/base_preliminar.xlsx')
ministerio = pd.read_csv('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/pesa_ministerio_site.csv', sep=';')

In [26]:
# Filtra somente os pesas comm SAESc
ministerio = ministerio[ministerio['ATENDIMENTOS'].str.contains('escorp', case=False, na=False)].copy()

In [28]:
# Normaliza a coluna MUNICIPIO
from unidecode import unidecode   # Importa função que remove acentos e caracteres Unicode

ministerio['MUNICIPIO'] = (               # Sobrescreve a coluna 'municipio' com o texto padronizado
   ministerio['MUNICIPIO']
   .astype(str)    # Converte todos os valores para texto (string)
                                 # Evita erro caso existam números, NaN etc.
   .apply(unidecode)             # Remove acentos e caracteres especiais Unicode
                                 # Ex: "São João" -> "Sao Joao"
   .str.upper()                  # Transforma todo o texto em CAIXA ALTA
                                 # Ex: "Sao Joao" -> "SAO JOAO"
                     # Indica que o padrão é uma expressão regular
   ) .str.strip()               # Remove espaços no início e fim do texto, Ex: " SAO JOAO " -> "SAO JOAO"

'''.str.replace(r'[^A-Z0-9\s]',  # Expressão regular:
                                 # [^ ... ] = tudo que NÃO estiver dentro
                                 # A-Z = letras maiúsculas
                                 # 0-9 = números
                                 # \s = espaços
                                 # Portanto remove pontuação, hífen, vírgula etc.
    '',                         # Substitui os caracteres encontrados por vazio, Ou seja, remove
    regex=True'''

".str.replace(r'[^A-Z0-9\\s]',  # Expressão regular:\n                                 # [^ ... ] = tudo que NÃO estiver dentro\n                                 # A-Z = letras maiúsculas\n                                 # 0-9 = números\n                                 # \\s = espaços\n                                 # Portanto remove pontuação, hífen, vírgula etc.\n    '',                         # Substitui os caracteres encontrados por vazio, Ou seja, remove\n    regex=True"

In [31]:
ministerio.to_csv('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/pesa_ministerio_site.csv', sep=';', index=False)

In [24]:
ministerio[~ministerio['MUNICIPIO'].isin(df['PESA'])]

,MUNICIPIO,UNIDADE,ENDERECO,TELEFONES,CNES,ATENDIMENTOS
16,BARIRI,Santa Casa de Misericórdia de Bariri,"Avenida Coronel Antônio José de\nCarvalho,409,...",(14) 36626522,2791676.0,Escorpiônico
17,BARRA BONITA,HOSPITAL E MATERNIDADE SÃO JOSÉ,"RUA 14 DE DEZEMBRO,490-CENTRO",(14) 36417114,2082632.0,Escorpiônico
26,BOCAINA,Santa casa de\nMisericórdia de Bocaina,"Rua Cerqueira César,239 - Centro",(14) 3666-1190,2791730.0,Escorpiônico
27,BORACEIA,Pronto Atendimento\nMunicipal de Boracéia,"Rua Antônio de Freitas Pereira, 300 - Centro",(14)32959105,9276203.0,Escorpiônico
30,BROTAS,Hospital Santa Terezinha,"Av. Rui Barbosa, 703 - Centro, Brotas - SP, CE...",(14)3653-9100,2665883.0,"Botrópico, Crotálico, Loxoscélico, Fonêutrico ..."
55,DOIS CORREGOS,Santa Casa de\nMisericórdia de Dois Corrégos,"Avenida Dr Joaquim\nRoberto de Carvalho Pinto,...",(14) 36521211 -\n3652 9933,2791692.0,Escorpiônico
65,FERRAZ DE\nVASCONCELOS,Hospital Dr. Osíris\nFlorindo Coelho,"R. Princesa Isabel, 270-\nVila Correa",(11) 4675.3444,2080079.0,Escorpiônico
81,IGARACU DO TIETE,UPA -Domingos Bergamasco,"Rua Maria do Carmo Nicolette Ortega,168",14997103613,2962888.0,Escorpiônico
92,ITAPECERICA SERRA,Maternidade Municipal Zoraide\nEva das Dores,"Rua Carlos Eduardo D. Tautico, 77 - Centro",(11) 4668-6803,2086271.0,"Botrópico, Crotálico, Loxoscélico, Fonêutrico ..."
98,ITAPOLIS,SANTA CASA DE MISERICÓRDIA DE\nITÁPOLIS,NaN,NaN,NaN,"BOTRÓPICO, CROTÁLICO, Loxoscélico, Fonêutrico ..."
99,ITAPUI,Hospital São José\n- Itapui,"Avenida Paes de Barros,326-Centro",(14) 3664-8040,2079224.0,Escorpiônico
123,MACAUBAL,Santa Casa de Macaubal,"RUA SETE DE SETEMBRO, Nº 1203 - CENTRO, 15270-...",(17)3874-1408,2081792.0,Escorpiônico
129,MINEIROS DO TIETE,Pronto Atendimento\nMunicipal de Mineiros do T...,"Rua Subdelegado Ferrinho,535-Centro",(14) 3646-3800 -\n36461217,4048725.0,Escorpiônico
132,MIRANTE DO\nPARANAPANEMA,AME Mirante,"Avenida Zil Brasil, 320 -\nCentro",(18) 3991-1292,2062852.0,"Botrópico, Crotálico, Escorpiônico e\nLoxoscél..."
139,MONTE APRAZIVEL,Irmandade da Santa casa de Misericórdia\nde Mo...,"RUA SÃO JOÃO, 729, CENTRO, 15150-000",(17)3275-9510,2082667.0,Escorpiônico
142,NOVA CAMPINA,Unidade de Saúde João Rodrigues de\nProença,"R. JOÃO NUNES DE OLIVEIRA, 525 - CENTRO -\n184...",(15) 3535-1264,2063999.0,"Escorpiônico e Loxoscélico, Fonêutrico"
146,ORINDIUVA,Santa Casa de Orindiúva,"AV. FRANCISCO TOMÁS AQUINO, 170 - 250, ORINDIÚ...",(17)3816-1297,2063018.0,"Botrópico, Crotálico e Escorpiônico"
151,PARAGUACU\nPAULISTA,Santa Casa de\nParaguaçu Paulista,"Rua Caramuru, 568 -\nCentro",(18) 3361-1133,2082519.0,"Botrópico, Crotálico, Loxoscélico,\nFonêutrico..."
156,PAULINIA,Hospital Municipal de Paulínia,"R. Miguel Vicente Cury, 100 - Nova Paulínia,\n...",(19) 3874-5500,2081059.0,Escorpiônico
172,PRESIDENTE\nEPITACIO,Santa Casa de\nPresidente Epitácio,"Rua Antonio Venâncio\nLopes, 942 - Vila Maria",(18) 3251-8010,2751038.0,"Botrópico, Crotálico, Escorpiônico e\nLoxoscél..."
176,PROMISSAO,Hospital Geral de Promissão,"Av. Gen. Euríco Gaspar Dutra, 620 - Centro, Pr...",(14) 3541-0644,2790610.0,"Botrópico, Crotálico, Loxoscélico, Fonêutrico ..."
189,SANTA CRUZ DO RIO\nPARDO,Santa Casa de Santa\nCruz do Rio Pardo,"AV. DR. CIRO DE MELLO\nCAMARINHA 530, CENTRO",(14) 3332-1222,2084058.0,"Botrópico, Crotálico, Loxoscélico,\nFonêutrico..."
192,SANTA RITA DO\nPASSA QUATRO,"Santa Casa Santa Rita Rua Inácio Ribeiro, ...",NaN,NaN,2091267.0,"Botrópico, Crotálico e Escorpiônico."
200,SAO JOAQUIM DA\nBARRA,Santa Casa de São\nJoaquim da Barra,"Rua Piratininga, 1221 -\nCentro",(16) 3810-4000,2080044.0,"Botrópico, Crotálico, Loxoscélico,\nFonêutrico..."
201,SAO JOSE DO\nBARREIRO,Unidade Mista de\nSaúde Dr. Acácio,"Rua José Bento Teixeira,\ns/n - Centro",(12) 3117-1339,2079771.0,"Botrópico, Crotálico, Escorpiônico e\nLoxoscél..."
202,SAO JOSE DO RIO\nPARDO,Hospital São Vicente,"Rua Coronel Alípio Dias,\n620 - Centro",(19) 3682-7826/3608-\n7484,2080923.0,"Botrópico, Crotálico, Escorpiônico,\nLoxoscéli..."
207,SAO JOSE DOS\nCAMPOS,HOSPITAL DE\nCLÍNICAS SUL,"PRAÇA NATAL, 55 PARQUE\nINDUSTRIAL",(12)3935-8100,26417.0,Escorpiônico
209,SAO JOSE DOS\nCAMPOS,UPA São Francisco\nXavier,"Rua Quinze de Novembro,\ns/n - Centro",(12) 3926-1266,9164.0,"Botrópico, Crotálico, Loxoscélico,\nFonêutrico..."
210,SAO LUIS DO\nPARAITINGA,Santa Casa de\nMisericórdia,"Praça Coronel Teodoro\nCoelho, 48 - Centro",(12) 3671-1299,2079690.0,"Botrópico, Crotálico, Escorpiônico e\nLoxoscél..."
235,TORRINHA,Hospital Padre Nicanor Merino,"Rua Angelo Bartolai,126\n- Centro",(14) 3656-1414,2080605.0,Escorpiônico
239,URUPES,HOSPITAL SÃO LOURENÇO - URUPÊS,"R. BARÃO DO RIO BRANCO, 226-372,\nCENTRO - 158...",(17)3552-1339,2081342.0,Escorpiônico
242,MAUA,Hospital Nardini,"Rua Regente Feijó, 166.\nVila Bocaina",(11) 4747-6999,2082349.0,"Botrópico, Crotálico, Escorpiônico e\nLoxoscél..."
244,SAO JOSE DO RIO\nPRETO,UPA Tangará,"Av. Pres. Getúlio Vargas,\n381 – Jardim Tangará",(17) 3222-4184,7706766.0,Escorpiônico

In [24]:
ministerio

                  MUNICIPIO                                       ATENDIMENTOS
0                ADAMANTINA  Botrópico, Crotálico, Loxoscélico,\nFonêutrico...
1          AGUAS DE LINDOIA                                       Escorpiônico
2               ALTINOPOLIS               Botrópico, Crotálico e Escorpiônico.
3                 AMERICANA            Escorpiônico e Loxoscélico, Fonêutrico.
4                    AMPARO  Botrópico, Crotálico, Escorpiônico e\nLoxoscél...
..                      ...                                                ...
240              VALPARAISO  Botrópico, Crotálico, Loxoscélico,\nFonêutrico...
241             VOTUPORANGA  Botrópico, Crotálico, Escorpiônico e\nLoxoscél...
242                    MAUA  Botrópico, Crotálico, Escorpiônico e\nLoxoscél...
243   SAO JOSE DO RIO PRETO                                       Escorpiônico
244  SAO JOSE DO RIO\nPRETO                                       Escorpiônico

[242 rows x 2 columns]