In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('/home/costela/Documentos/Escorpiao_pesa/Quadro2/dados/base_preliminar.xlsx')
ministerio = pd.read_csv('/home/costela/Documentos/Escorpiao_pesa/Quadro2/dados/pesa_ministerio_site.csv', sep=';')

# df = pd.read_excel('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/base_preliminar.xlsx')
# ministerio = pd.read_csv('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/pesa_ministerio_site.csv', sep=';')

In [4]:
# Filtra somente os pesas comm SAESc
ministerio = ministerio[ministerio['ATENDIMENTOS'].str.contains('escorp', case=False, na=False)].copy()

In [11]:
# Normaliza o texto a coluna MUNICIPIO
from unidecode import unidecode   # Importa função que remove acentos e caracteres Unicode

ministerio['MUNICIPIO'] = (               # Sobrescreve a coluna 'municipio' com o texto padronizado
   ministerio['MUNICIPIO']
   .astype(str)    # Converte todos os valores para texto (string)
                                 # Evita erro caso existam números, NaN etc.
   .apply(unidecode)             # Remove acentos e caracteres especiais Unicode
                                 # Ex: "São João" -> "Sao Joao"
   .str.upper()                  # Transforma todo o texto em CAIXA ALTA
                                 # Ex: "Sao Joao" -> "SAO JOAO"
                     # Indica que o padrão é uma expressão regular
   ) .str.strip()               # Remove espaços no início e fim do texto, Ex: " SAO JOAO " -> "SAO JOAO"

'''.str.replace(r'[^A-Z0-9\s]',  # Expressão regular:
                                 # [^ ... ] = tudo que NÃO estiver dentro
                                 # A-Z = letras maiúsculas
                                 # 0-9 = números
                                 # \s = espaços
                                 # Portanto remove pontuação, hífen, vírgula etc.
    '',                         # Substitui os caracteres encontrados por vazio, Ou seja, remove
    regex=True'''

<>:15: SyntaxWarning: invalid escape sequence '\s'
<>:15: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_14740/750541055.py:15: SyntaxWarning: invalid escape sequence '\s'
  '''.str.replace(r'[^A-Z0-9\s]',  # Expressão regular:

".str.replace(r'[^A-Z0-9\\s]',  # Expressão regular:\n                                 # [^ ... ] = tudo que NÃO estiver dentro\n                                 # A-Z = letras maiúsculas\n                                 # 0-9 = números\n                                 # \\s = espaços\n                                 # Portanto remove pontuação, hífen, vírgula etc.\n    '',                         # Substitui os caracteres encontrados por vazio, Ou seja, remove\n    regex=True"

In [12]:
# Contagem do número de PESA por municipio 
n_pesa = ministerio['MUNICIPIO'].value_counts(dropna=False).reset_index()
n_pesa.columns = ['PESA_SITE', 'N_PESA']

## Continuar daqui

In [13]:
#n_pesa.info()
df['MUNI_REFERENCIADO'].info()

<class 'pandas.Series'>
RangeIndex: 645 entries, 0 to 644
Series name: MUNI_REFERENCIADO
Non-Null Count  Dtype
--------------  -----
645 non-null    str
dtypes: str(1)
memory usage: 5.2 KB

In [24]:
# Merge do numero de PESA ao df

df = df.merge(
    n_pesa,
    left_on="MUNI_REFERENCIADO",
    right_on="PESA_SITE",
    how="left"
)
df

,Unnamed: 0,ACESSO_LOCAL,MULTIPLO_PESA,REGIAO,PESA,MUNI_REFERENCIADO,OBSERVACOES,LAT_MUNI,LON_MUNI,LAT_PESA,...,MG_ORIGINAL,LEVE_10,MG_10,LEVE_11A59,MG_11A59,LEVE_60,MG_60,TOTAL_AMPOLAS,PESA_SITE,N_PESA
0,0,0,0,ARACATUBA,PENAPOLIS,ALTO ALEGRE,TODOS,-21.582059,-50.166198,-21.416404,...,10,7,1,93,0,52,1,2,NaN,NaN
1,1,0,0,ARACATUBA,PENAPOLIS,AVANHANDAVA,TODOS,-21.460333,-49.946516,-21.416404,...,13,12,2,95,5,18,0,9,NaN,NaN
2,2,0,0,ARACATUBA,PENAPOLIS,BARBOSA,TODOS,-21.265661,-49.951816,-21.416404,...,7,33,2,233,1,61,0,4,NaN,NaN
3,3,0,0,ARACATUBA,VALPARAISO,BENTO DE ABREU,TODOS,-21.271572,-50.811723,-21.230655,...,2,5,1,49,0,15,1,4,NaN,NaN
4,4,0,0,ARACATUBA,CLEMENTINA,BILAC,TODOS,-21.403962,-50.474640,-21.556698,...,8,8,0,65,1,28,2,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,640,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,IPIGUA,TODOS,0.000000,0.000000,0.000000,...,15,14,2,128,6,32,3,9,NaN,NaN
641,641,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,ONDA VERDE,TODOS,0.000000,0.000000,0.000000,...,18,30,5,154,7,26,2,6,NaN,NaN
642,642,1,0,PIRACICABA,PIRACICABA,PIRACICABA,TODOS,0.000000,0.000000,0.000000,...,106,583,64,5026,38,976,7,219,PIRACICABA,2.0
643,643,0,0,PIRACICABA,PIRACICABA,RIO DAS PEDRAS,TODOS,0.000000,0.000000,0.000000,...,6,18,2,85,1,21,0,5,NaN,NaN
644,644,1,0,CARAGUATATUBA,ILHABELA,ILHABELA,TODOS,0.000000,0.000000,0.000000,...,0,1,0,6,0,0,0,3,ILHABELA,1.0

In [28]:
n_pesa[~n_pesa['PESA_SITE'].isin(df['MUNI_REFERENCIADO'])]

                       PESA_SITE  N_PESA
72        FERRAZ DE\nVASCONCELOS       1
133     MIRANTE DO\nPARANAPANEMA       1
152          PARAGUACU\nPAULISTA       1
171         PRESIDENTE\nEPITACIO       1
184     SANTA CRUZ DO RIO\nPARDO       1
187  SANTA RITA DO\nPASSA QUATRO       1
195        SAO JOAQUIM DA\nBARRA       1
196        SAO JOSE DO\nBARREIRO       1
197       SAO JOSE DO RIO\nPARDO       1
198      SAO LUIS DO\nPARAITINGA       1
220       SAO JOSE DO RIO\nPRETO       1

In [32]:
df.loc[df['MUNI_REFERENCIADO'].isin(['FERRAZ DE VASCONCELOS','MIRANTE DO PARANAPANEMA','PARAGUACU PAULISTA','PRESIDENTE EPITACIO',
'SANTA CRUZ DO RIO PARDO','SANTA RITA DO PASSA QUATRO','SAO JOAQUIM DA BARRA','SAO JOSE DO BARREIRO',
'SAO JOSE DO RIO PARDO','SAO LUIS DO PARAITINGA'
#,'SAO JOSE DO RIO PRETO'
]),['PESA_SITE', 'N_PESA']]

    PESA_SITE  N_PESA
218       NaN     NaN
463       NaN     NaN
464       NaN     NaN
502       NaN     NaN
520       NaN     NaN
522       NaN     NaN
547       NaN     NaN
565       NaN     NaN
609       NaN     NaN
610       NaN     NaN

In [27]:
df.groupby('PESA_SITE')['N_PESA'].sum().reset_index().sort_values('N_PESA', ascending=False)

                 PESA_SITE  N_PESA
188              SAO PAULO     7.0
185  SAO JOSE DO RIO PRETO     4.0
186    SAO JOSE DOS CAMPOS     4.0
106                JUNDIAI     2.0
72               GUARULHOS     2.0
..                     ...     ...
74                IBITINGA     1.0
75                    IEPE     1.0
76        IGARACU DO TIETE     1.0
77               IGARAPAVA     1.0
209            VOTUPORANGA     1.0

[210 rows x 2 columns]