In [19]:
import pandas as pd

In [20]:
df = pd.read_excel('dados/base_analise.xlsx')

## 1. Rede assistencial
* número de PESA (municípios com acesso local);
* municípios referenciados;
* tempo, distância medianos e percentis;
* faixas críticas.
* cobertura de pesa por região
* taxa de pesa por população

In [21]:
# Número de PESA
df[df['ACESSO_LOCAL']==1].shape

(220, 51)

In [22]:
# Número de municípios sem PESA
df[df['ACESSO_LOCAL']==0].shape[0]

425

In [23]:
# Tempo de acesso médio para municípios sem PESA
df[df['ACESSO_LOCAL']==0]['TEMPO'].describe().round(1)

count    425.0
mean      27.4
std       12.0
min        6.8
25%       19.0
50%       25.2
75%       34.3
max       70.8
Name: TEMPO, dtype: float64

In [24]:
# Tempo médio de acesso para municípios sem PESA por Região
df[df['ACESSO_LOCAL']==0].groupby('REGIAO')['TEMPO'].describe().round(1)

                       count  mean   std   min   25%   50%   75%   max
REGIAO
ARACATUBA               25.0  23.3   8.8  10.6  15.9  22.3  28.1  47.5
ARARAQUARA              17.0  30.6  11.3  15.6  22.7  28.5  37.2  54.1
ASSIS                   21.0  29.4  11.9  12.1  20.9  25.8  40.1  57.5
BARRETOS                12.0  30.6  11.4  15.7  23.8  29.9  35.8  57.6
BAURU                   21.0  27.6  12.5   9.8  18.4  23.5  36.2  56.3
BOTUCATU                22.0  34.7  14.9  13.2  21.1  32.4  48.1  63.5
CAMPINAS                29.0  26.5  13.1   8.7  18.1  24.1  33.3  70.8
FRANCA                  13.0  19.6   7.8  10.4  13.1  17.9  24.3  34.3
FRANCO DA ROCHA          2.0  29.2   7.4  24.0  26.6  29.2  31.9  34.5
ITAPEVA                  6.0  41.7  17.9  21.8  27.1  41.2  57.8  60.2
JALES                   31.0  25.0  10.2   8.7  18.0  22.5  31.6  51.7
MARILIA                 33.0  34.2  12.7   8.5  26.6  34.1  42.1  61.6
MOGI DAS CRUZES          6.0  18.3   7.9   7.4  12.6  19.6  24.1  27.2
OSASCO                  10.0  21.3   8.0   8.6  16.2  19.2  27.0  32.9
PIRACICABA              17.0  18.7   7.4   6.8  13.6  19.2  24.0  32.9
PRESIDENTE PRUDENTE     18.0  24.4  10.5  10.4  19.1  21.5  29.6  48.5
PRESIDENTE VENCESLAU    11.0  20.5   6.3  11.5  15.6  19.8  24.4  30.3
RIBEIRAO PRETO          18.0  27.0   9.4  14.0  20.2  26.4  32.0  46.4
SANTO ANDRE              5.0  25.8  13.1  14.2  16.2  21.0  31.9  45.9
SANTOS                   1.0  12.1   NaN  12.1  12.1  12.1  12.1  12.1
SAO JOAO DA BOA VISTA   11.0  19.8   6.6  10.3  15.2  19.9  22.2  35.2
SAO JOSE DO RIO PRETO   53.0  31.5  11.6  11.9  23.3  31.3  39.0  60.7
SAO JOSE DOS CAMPOS      3.0  23.7   1.7  22.3  22.8  23.2  24.4  25.6
SOROCABA                25.0  28.3   9.1   7.7  23.7  28.1  36.7  42.6
TAUBATE                 15.0  24.7  15.8  11.0  12.3  18.6  26.8  63.7

In [25]:
# Municípios com Tempo crítico por Região
df.loc[(df['ACESSO_LOCAL']==0) & (df['TEMPO']>59),['REGIAO','MUNI','TEMPO']]

                    REGIAO                    MUNI  TEMPO
117               BOTUCATU               PORANGABA  63.50
141               CAMPINAS                PIRACAIA  70.80
162                ITAPEVA  BOM SUCESSO DE ITARARE  60.20
165                ITAPEVA                 RIBEIRA  59.10
328  SAO JOSE DO RIO PRETO                  IRAPUA  60.70
392                TAUBATE     NATIVIDADE DA SERRA  63.70
429                MARILIA               UBIRAJARA  61.65

In [26]:
# Número de PESA, Municipio e População por Região

# - Número de PESA por Região
pesaReg = df[df['ACESSO_LOCAL']==1].groupby('REGIAO').size().reset_index(name='N_PESA')

# - Número de Municípios por Região
muniReg = df.groupby('REGIAO').size().reset_index(name='N_MUNICIPIOS')

# - População por Região
popReg = df.groupby('REGIAO')['POP_GERAL'].sum().reset_index(name='POP_REG')

# Merge Regiao, Pesa e contagens de Pesa
dfReg = pesaReg.merge(muniReg,on = 'REGIAO')

# Merge Regiao e População da Região
dfReg = dfReg.merge(popReg,on = 'REGIAO')

In [ ]:
# Cobertura de Pesa por Região
dfReg['COB_PESA'] = (dfReg['N_PESA'] / dfReg['N_MUNICIPIOS']*100).round(1)

                   REGIAO  N_PESA  N_MUNICIPIOS   POP_REG  COB_PESA
0               ARACATUBA      15            40    778764      37.5
1              ARARAQUARA       7            24   1017893      29.2
2                   ASSIS       4            25    477766      16.0
3                BARRETOS       6            18    438357      33.3
4                   BAURU      17            38   1154860      44.7
5                BOTUCATU       8            30    618794      26.7
6                CAMPINAS      13            42   4733979      31.0
7           CARAGUATATUBA       4             4    349708     100.0
8                  FRANCA       9            22    700936      40.9
9         FRANCO DA ROCHA       3             5    605130      60.0
10                ITAPEVA       9            15    280506      60.0
11                  JALES       4            35    281670      11.4
12                MARILIA       4            37    655299      10.8
13        MOGI DAS CRUZES       5            11   3008699      45.5
14                 OSASCO       5            15   3149328      33.3
15             PIRACICABA       9            26   1590372      34.6
16    PRESIDENTE PRUDENTE       6            24    474069      25.0
17   PRESIDENTE VENCESLAU      10            21    291444      47.6
18               REGISTRO      15            15    284892     100.0
19         RIBEIRAO PRETO       8            26   1501111      30.8
20            SANTO ANDRE       2             7   2784910      28.6
21                 SANTOS       8             9   1850396      88.9
22  SAO JOAO DA BOA VISTA       9            20    826053      45.0
23  SAO JOSE DO RIO PRETO      14            67   1388728      20.9
24    SAO JOSE DOS CAMPOS       5             8   1117185      62.5
25              SAO PAULO       1             1  11950472     100.0
26               SOROCABA       8            33   2323307      24.2
27                TAUBATE      12            27   1102350      44.4

In [29]:
# População por Pesa
dfReg['POP_POR_PESA'] = (dfReg['POP_REG'] / dfReg['N_PESA']).round(1)

In [30]:
dfReg

,REGIAO,N_PESA,N_MUNICIPIOS,POP_REG,COB_PESA,POP_POR_PESA
0,ARACATUBA,15,40,778764,37.5,51917.6
1,ARARAQUARA,7,24,1017893,29.2,145413.3
2,ASSIS,4,25,477766,16.0,119441.5
3,BARRETOS,6,18,438357,33.3,73059.5
4,BAURU,17,38,1154860,44.7,67932.9
5,BOTUCATU,8,30,618794,26.7,77349.2
6,CAMPINAS,13,42,4733979,31.0,364152.2
7,CARAGUATATUBA,4,4,349708,100.0,87427.0
8,FRANCA,9,22,700936,40.9,77881.8
9,FRANCO DA ROCHA,3,5,605130,60.0,201710.0
10,ITAPEVA,9,15,280506,60.0,31167.3
11,JALES,4,35,281670,11.4,70417.5
12,MARILIA,4,37,655299,10.8,163824.8
13,MOGI DAS CRUZES,5,11,3008699,45.5,601739.8
14,OSASCO,5,15,3149328,33.3,629865.6
15,PIRACICABA,9,26,1590372,34.6,176708.0
16,PRESIDENTE PRUDENTE,6,24,474069,25.0,79011.5
17,PRESIDENTE VENCESLAU,10,21,291444,47.6,29144.4
18,REGISTRO,15,15,284892,100.0,18992.8
19,RIBEIRAO PRETO,8,26,1501111,30.8,187638.9
20,SANTO ANDRE,2,7,2784910,28.6,1392455.0
21,SANTOS,8,9,1850396,88.9,231299.5
22,SAO JOAO DA BOA VISTA,9,20,826053,45.0,91783.7
23,SAO JOSE DO RIO PRETO,14,67,1388728,20.9,99194.9
24,SAO JOSE DOS CAMPOS,5,8,1117185,62.5,223437.0
25,SAO PAULO,1,1,11950472,100.0,11950472.0
26,SOROCABA,8,33,2323307,24.2,290413.4
27,TAUBATE,12,27,1102350,44.4,91862.5

In [28]:
df.columns

Index(['Unnamed: 0', 'ACESSO_LOCAL', 'MULTIPLO_PESA', 'REGIAO', 'PESA', 'MUNI',
       'OBSERVACOES', 'LAT_MUNI', 'LON_MUNI', 'LAT_PESA', 'LON_PESA',
       'DISTANCIA', 'TEMPO', 'IBGE', 'POP10', 'POP11A59', 'POP60', 'POP_GERAL',
       'TOTAL_CASOS', 'TOTAL_10A', 'TOTAL_11A59', 'TOTAL_60', 'LEVE', 'MG',
       'MG_ORIGINAL', 'LEVE_10', 'MG_10', 'LEVE_11A59', 'MG_11A59', 'LEVE_60',
       'MG_60', 'TOTAL_AMPOLAS', 'N_PESA', 'CAT_TEMPO', 'PROP_POP_0A10',
       'PROP_POP_60MAIS', 'LOG_POP', 'PROP_MG', 'INCID_MEDIA_GERAL',
       'INCID_0A10', 'INCID_60MAIS', 'PROP_CASOS_0A10', 'PROP_CASOS_60MAIS',
       'TAXA_MG_100MIL', 'CLASS_IG', 'SORO_IG', 'EVOL_IG', 'PROP_CLASS_IGN',
       'PROP_SORO_IGN', 'PROP_EVOL_IGN', 'BAIXO_N'],
      dtype='str')

## 2. Perfil epidemiológico
* casos totais;
* incidência média anual;
* registros MG;
* proporção de crianças e idosos;
* distribuição municipal.

## 3. Integração entre demanda e acesso
* casos e MG por faixas de tempo;
* casos e MG por faixas de distância;
* mapas de demanda versus acessibilidade;
* municípios com alta incidência e maior tempo de acesso.

## 4. Comparação temporal
* 2015–2019 versus 2020–2023;
* variação na incidência;
* variação na proporção MG;
* mudança na concentração espacial;
* estabilidade ou alteração das faixas de acesso.