In [111]:
import pandas as pd
import heapq

In [112]:
df = pd.read_excel('dados/base_analise.xlsx')

## 1. Rede assistencial
* número de PESA (municípios com acesso local);
* municípios referenciados;
* tempo, distância medianos e percentis;
* faixas críticas.
* cobertura de pesa por região
* relação de numero de habitantes por pesa na região

In [113]:
# Número de PESA
df[df['ACESSO_LOCAL']==1].shape

(220, 51)

In [114]:
# Número de municípios sem PESA
df[df['ACESSO_LOCAL']==0].shape[0]

425

In [115]:
# Tempo de acesso médio para municípios sem PESA
df[df['ACESSO_LOCAL']==0]['TEMPO'].describe().round(1)

count    425.0
mean      27.4
std       12.0
min        6.8
25%       19.0
50%       25.2
75%       34.3
max       70.8
Name: TEMPO, dtype: float64

In [116]:
# Tempo médio de acesso para municípios sem PESA por Região
df[df['ACESSO_LOCAL']==0].groupby('REGIAO')['TEMPO'].describe().round(1)

                       count  mean   std   min   25%   50%   75%   max
REGIAO
ARACATUBA               25.0  23.3   8.8  10.6  15.9  22.3  28.1  47.5
ARARAQUARA              17.0  30.6  11.3  15.6  22.7  28.5  37.2  54.1
ASSIS                   21.0  29.4  11.9  12.1  20.9  25.8  40.1  57.5
BARRETOS                12.0  30.6  11.4  15.7  23.8  29.9  35.8  57.6
BAURU                   21.0  27.6  12.5   9.8  18.4  23.5  36.2  56.3
BOTUCATU                22.0  34.7  14.9  13.2  21.1  32.4  48.1  63.5
CAMPINAS                29.0  26.5  13.1   8.7  18.1  24.1  33.3  70.8
FRANCA                  13.0  19.6   7.8  10.4  13.1  17.9  24.3  34.3
FRANCO DA ROCHA          2.0  29.2   7.4  24.0  26.6  29.2  31.9  34.5
ITAPEVA                  6.0  41.7  17.9  21.8  27.1  41.2  57.8  60.2
JALES                   31.0  25.0  10.2   8.7  18.0  22.5  31.6  51.7
MARILIA                 33.0  34.2  12.7   8.5  26.6  34.1  42.1  61.6
MOGI DAS CRUZES          6.0  18.3   7.9   7.4  12.6  19.6  24.1  27.2
OSASCO                  10.0  21.3   8.0   8.6  16.2  19.2  27.0  32.9
PIRACICABA              17.0  18.7   7.4   6.8  13.6  19.2  24.0  32.9
PRESIDENTE PRUDENTE     18.0  24.4  10.5  10.4  19.1  21.5  29.6  48.5
PRESIDENTE VENCESLAU    11.0  20.5   6.3  11.5  15.6  19.8  24.4  30.3
RIBEIRAO PRETO          18.0  27.0   9.4  14.0  20.2  26.4  32.0  46.4
SANTO ANDRE              5.0  25.8  13.1  14.2  16.2  21.0  31.9  45.9
SANTOS                   1.0  12.1   NaN  12.1  12.1  12.1  12.1  12.1
SAO JOAO DA BOA VISTA   11.0  19.8   6.6  10.3  15.2  19.9  22.2  35.2
SAO JOSE DO RIO PRETO   53.0  31.5  11.6  11.9  23.3  31.3  39.0  60.7
SAO JOSE DOS CAMPOS      3.0  23.7   1.7  22.3  22.8  23.2  24.4  25.6
SOROCABA                25.0  28.3   9.1   7.7  23.7  28.1  36.7  42.6
TAUBATE                 15.0  24.7  15.8  11.0  12.3  18.6  26.8  63.7

In [117]:
# Municípios com Tempo crítico por Região
df.loc[(df['ACESSO_LOCAL']==0) & (df['TEMPO']>59),['REGIAO','MUNI','TEMPO']]

                    REGIAO                    MUNI  TEMPO
117               BOTUCATU               PORANGABA  63.50
141               CAMPINAS                PIRACAIA  70.80
162                ITAPEVA  BOM SUCESSO DE ITARARE  60.20
165                ITAPEVA                 RIBEIRA  59.10
328  SAO JOSE DO RIO PRETO                  IRAPUA  60.70
392                TAUBATE     NATIVIDADE DA SERRA  63.70
429                MARILIA               UBIRAJARA  61.65

In [118]:
# Número de PESA, Municipio e População por Região

# - Número de PESA por Região
pesaReg = df[df['ACESSO_LOCAL']==1].groupby('REGIAO').size().reset_index(name='N_PESA')

# - Número de Municípios por Região
muniReg = df.groupby('REGIAO').size().reset_index(name='N_MUNICIPIOS')

# - População por Região
popReg = df.groupby('REGIAO')['POP_GERAL'].sum().reset_index(name='POP_REG')

# Merge Regiao, Pesa e contagens de Pesa
dfReg = pesaReg.merge(muniReg,on = 'REGIAO')

# Merge Regiao e População da Região
dfReg = dfReg.merge(popReg,on = 'REGIAO')

In [119]:
# Cobertura de Pesa por Região
dfReg['COB_PESA'] = (dfReg['N_PESA'] / dfReg['N_MUNICIPIOS']*100).round(1)

In [120]:
# População por Pesa
dfReg['POP_POR_PESA'] = (dfReg['POP_REG'] / dfReg['N_PESA']).round(1)

In [121]:
dfReg

,REGIAO,N_PESA,N_MUNICIPIOS,POP_REG,COB_PESA,POP_POR_PESA
0,ARACATUBA,15,40,778764,37.5,51917.6
1,ARARAQUARA,7,24,1017893,29.2,145413.3
2,ASSIS,4,25,477766,16.0,119441.5
3,BARRETOS,6,18,438357,33.3,73059.5
4,BAURU,17,38,1154860,44.7,67932.9
5,BOTUCATU,8,30,618794,26.7,77349.2
6,CAMPINAS,13,42,4733979,31.0,364152.2
7,CARAGUATATUBA,4,4,349708,100.0,87427.0
8,FRANCA,9,22,700936,40.9,77881.8
9,FRANCO DA ROCHA,3,5,605130,60.0,201710.0
10,ITAPEVA,9,15,280506,60.0,31167.3
11,JALES,4,35,281670,11.4,70417.5
12,MARILIA,4,37,655299,10.8,163824.8
13,MOGI DAS CRUZES,5,11,3008699,45.5,601739.8
14,OSASCO,5,15,3149328,33.3,629865.6
15,PIRACICABA,9,26,1590372,34.6,176708.0
16,PRESIDENTE PRUDENTE,6,24,474069,25.0,79011.5
17,PRESIDENTE VENCESLAU,10,21,291444,47.6,29144.4
18,REGISTRO,15,15,284892,100.0,18992.8
19,RIBEIRAO PRETO,8,26,1501111,30.8,187638.9
20,SANTO ANDRE,2,7,2784910,28.6,1392455.0
21,SANTOS,8,9,1850396,88.9,231299.5
22,SAO JOAO DA BOA VISTA,9,20,826053,45.0,91783.7
23,SAO JOSE DO RIO PRETO,14,67,1388728,20.9,99194.9
24,SAO JOSE DOS CAMPOS,5,8,1117185,62.5,223437.0
25,SAO PAULO,1,1,11950472,100.0,11950472.0
26,SOROCABA,8,33,2323307,24.2,290413.4
27,TAUBATE,12,27,1102350,44.4,91862.5

In [122]:
df.columns

Index(['Unnamed: 0', 'ACESSO_LOCAL', 'MULTIPLO_PESA', 'REGIAO', 'PESA', 'MUNI',
       'OBSERVACOES', 'LAT_MUNI', 'LON_MUNI', 'LAT_PESA', 'LON_PESA',
       'DISTANCIA', 'TEMPO', 'IBGE', 'POP10', 'POP11A59', 'POP60', 'POP_GERAL',
       'TOTAL_CASOS', 'TOTAL_10A', 'TOTAL_11A59', 'TOTAL_60', 'LEVE', 'MG',
       'MG_ORIGINAL', 'LEVE_10', 'MG_10', 'LEVE_11A59', 'MG_11A59', 'LEVE_60',
       'MG_60', 'TOTAL_AMPOLAS', 'N_PESA', 'CAT_TEMPO', 'PROP_POP_0A10',
       'PROP_POP_60MAIS', 'LOG_POP', 'PROP_MG', 'INCID_MEDIA_GERAL',
       'INCID_0A10', 'INCID_60MAIS', 'PROP_CASOS_0A10', 'PROP_CASOS_60MAIS',
       'TAXA_MG_100MIL', 'CLASS_IG', 'SORO_IG', 'EVOL_IG', 'PROP_CLASS_IGN',
       'PROP_SORO_IGN', 'PROP_EVOL_IGN', 'BAIXO_N'],
      dtype='str')

## 2. Perfil epidemiológico
* total de casos;
* incidência média anual;
* total de MG;
* descritivo de MG no Estado
* total de MG por Região
* proporção de casos MG entre crianças e idosos nos municípios e nas Regiões;
* distribuição municipal.

In [123]:
# Total de casos e incidência média anual
print(
    'Total de casos:', df['TOTAL_CASOS'].sum(),
    '\n',
    'Incidência média anual:', (df['TOTAL_CASOS'].sum()/6).round(1)
)

Total de casos: 239086
 Incidência média anual: 39847.7

In [124]:
# Total de MG e Descritivo MG no ESP
print(
    'Total de MG:', df['MG'].sum(), '\n\n',
    'Descritivo de MG no ESP:', df['MG'].describe()
)

Total de MG: 8990

 Descritivo de MG no ESP: count    645.000000
mean      13.937984
std       31.633222
min        0.000000
25%        2.000000
50%        5.000000
75%       13.000000
max      400.000000
Name: MG, dtype: float64

In [125]:
# Top 10 mais MG
df.loc[:, ['MUNI', 'MG']].nlargest(10, 'MG')

                      MUNI   MG
546         RIBEIRAO PRETO  400
635  SAO JOSE DO RIO PRETO  329
441              ARACATUBA  266
614               CAMPINAS  183
590               SOROCABA  178
611              SAO PAULO  176
472                    JAU  159
466              BEBEDOURO  148
443                BIRIGUI  147
642             PIRACICABA  143

In [126]:
# Total MG e Proporção por Região

temporaria = (
    df.groupby('REGIAO', as_index=False)
      .agg(
          TOTAL_MG=('MG', 'sum'),
          TOTAL_CASOS=('TOTAL_CASOS', 'sum')
      )
)
temporaria['PROP_MG'] = (
    temporaria['TOTAL_MG'] / temporaria['TOTAL_CASOS'] * 100
).round(1)

dfReg = dfReg.merge(
    temporaria,
    on='REGIAO',
    how='left'
)

dfReg

,REGIAO,N_PESA,N_MUNICIPIOS,POP_REG,COB_PESA,POP_POR_PESA,TOTAL_MG,TOTAL_CASOS,PROP_MG
0,ARACATUBA,15,40,778764,37.5,51917.6,999,33119,3.0
1,ARARAQUARA,7,24,1017893,29.2,145413.3,284,10748,2.6
2,ASSIS,4,25,477766,16.0,119441.5,138,5358,2.6
3,BARRETOS,6,18,438357,33.3,73059.5,467,8448,5.5
4,BAURU,17,38,1154860,44.7,67932.9,774,13718,5.6
5,BOTUCATU,8,30,618794,26.7,77349.2,153,4221,3.6
6,CAMPINAS,13,42,4733979,31.0,364152.2,641,18492,3.5
7,CARAGUATATUBA,4,4,349708,100.0,87427.0,6,44,13.6
8,FRANCA,9,22,700936,40.9,77881.8,371,8230,4.5
9,FRANCO DA ROCHA,3,5,605130,60.0,201710.0,60,1780,3.4
10,ITAPEVA,9,15,280506,60.0,31167.3,36,176,20.5
11,JALES,4,35,281670,11.4,70417.5,266,10356,2.6
12,MARILIA,4,37,655299,10.8,163824.8,352,10149,3.5
13,MOGI DAS CRUZES,5,11,3008699,45.5,601739.8,62,744,8.3
14,OSASCO,5,15,3149328,33.3,629865.6,62,1287,4.8
15,PIRACICABA,9,26,1590372,34.6,176708.0,366,17872,2.0
16,PRESIDENTE PRUDENTE,6,24,474069,25.0,79011.5,296,7456,4.0
17,PRESIDENTE VENCESLAU,10,21,291444,47.6,29144.4,361,11201,3.2
18,REGISTRO,15,15,284892,100.0,18992.8,9,114,7.9
19,RIBEIRAO PRETO,8,26,1501111,30.8,187638.9,818,18754,4.4
20,SANTO ANDRE,2,7,2784910,28.6,1392455.0,30,306,9.8
21,SANTOS,8,9,1850396,88.9,231299.5,11,69,15.9
22,SAO JOAO DA BOA VISTA,9,20,826053,45.0,91783.7,225,9387,2.4
23,SAO JOSE DO RIO PRETO,14,67,1388728,20.9,99194.9,1205,30979,3.9
24,SAO JOSE DOS CAMPOS,5,8,1117185,62.5,223437.0,82,1250,6.6
25,SAO PAULO,1,1,11950472,100.0,11950472.0,176,2805,6.3
26,SOROCABA,8,33,2323307,24.2,290413.4,421,6193,6.8
27,TAUBATE,12,27,1102350,44.4,91862.5,319,5830,5.5

In [127]:
# Proporção de MG por faixa etaria por município

# Proporção casos MG em crianças até 10 anos
df['PROP_CASOS_MG_10'] = (df['MG_10']/df['TOTAL_10A']*100).round(1)

# Proporção casos MG em pessoas de 11 a 59 anos
df['PROP_CASOS_MG_11A59'] = (df['MG_11A59']/df['TOTAL_11A59']*100).round(1)

# Proporção casos MG em pessoas com 60 anos ou mais
df['PROP_CASOS_MG_60'] = (df['MG_60']/df['TOTAL_60']*100).round(1)

In [128]:
# Describe por municipio
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,645.0,322.000000,186.339743,0.000000,161.000000,322.000000,483.000000,6.440000e+02
ACESSO_LOCAL,645.0,0.341085,0.474442,0.000000,0.000000,0.000000,1.000000,1.000000e+00
MULTIPLO_PESA,645.0,0.018605,0.135229,0.000000,0.000000,0.000000,0.000000,1.000000e+00
LAT_MUNI,645.0,-21.187495,4.659167,-25.010461,-23.006662,-22.115854,-21.096962,0.000000e+00
LON_MUNI,645.0,-46.533098,10.066311,-53.054797,-49.998726,-48.480188,-47.153221,0.000000e+00
LAT_PESA,645.0,-21.182265,4.657134,-25.011672,-22.983918,-22.195130,-21.061391,0.000000e+00
LON_PESA,645.0,-46.526231,10.062041,-52.949023,-49.978739,-48.496295,-47.175715,0.000000e+00
DISTANCIA,425.0,27.174922,13.572230,4.300000,17.800000,24.700000,34.200000,8.440000e+01
TEMPO,425.0,27.376395,11.996764,6.800000,19.000000,25.200000,34.300000,7.080000e+01
IBGE,645.0,352869.334884,1670.029961,350010.000000,351460.000000,352870.000000,354320.000000,3.557300e+05
POP10,645.0,9986.412403,65151.575397,142.000000,795.000000,1838.000000,5682.000000,1.601075e+06
POP11A59,645.0,49421.316279,339005.327788,595.000000,3749.000000,9246.000000,27533.000000,8.362476e+06
POP60,645.0,11502.314729,80233.632417,174.000000,1025.000000,2373.000000,7047.000000,1.986921e+06
POP_GERAL,645.0,70910.043411,484284.981587,911.000000,5536.000000,13464.000000,39698.000000,1.195047e+07
TOTAL_CASOS,645.0,370.675969,810.111618,0.000000,49.000000,139.000000,362.000000,9.924000e+03
TOTAL_10A,645.0,35.054264,81.543582,0.000000,4.000000,14.000000,33.000000,1.229000e+03
TOTAL_11A59,645.0,252.531783,560.496525,0.000000,35.000000,93.000000,250.000000,6.950000e+03
TOTAL_60,645.0,77.644961,164.511840,0.000000,8.000000,27.000000,80.000000,1.733000e+03
LEVE,645.0,356.737984,782.179241,0.000000,46.000000,133.000000,355.000000,9.524000e+03
MG,645.0,13.937984,31.633222,0.000000,2.000000,5.000000,13.000000,4.000000e+02
MG_ORIGINAL,645.0,17.539535,35.423837,0.000000,2.000000,7.000000,18.000000,4.040000e+02
LEVE_10,645.0,28.147287,65.983917,0.000000,3.000000,11.000000,27.000000,9.800000e+02
MG_10,645.0,6.906977,17.065931,0.000000,0.000000,2.000000,7.000000,2.490000e+02
LEVE_11A59,645.0,247.004651,550.585731,0.000000,33.000000,88.000000,243.000000,6.829000e+03
MG_11A59,645.0,5.527132,13.008166,0.000000,1.000000,2.000000,5.000000,1.570000e+02
LEVE_60,645.0,76.240310,161.888073,0.000000,7.000000,26.000000,80.000000,1.700000e+03
MG_60,645.0,1.404651,3.393771,0.000000,0.000000,0.000000,1.000000,3.700000e+01
TOTAL_AMPOLAS,645.0,41.826357,109.685013,0.000000,3.000000,13.000000,36.000000,1.649000e+03
N_PESA,645.0,0.375194,0.614528,0.000000,0.000000,0.000000,1.000000,7.000000e+00
PROP_POP_0A10,645.0,0.141209,0.017152,0.050000,0.130000,0.140000,0.150000,1.800000e-01
PROP_POP_60MAIS,645.0,0.179364,0.035641,0.080000,0.160000,0.180000,0.200000,3.200000e-01
LOG_POP,645.0,9.714642,1.435216,6.814543,8.619027,9.507775,10.589056,1.629628e+01
PROP_MG,638.0,0.053730,0.072136,0.000000,0.020000,0.030000,0.060000,5.000000e-01
INCID_MEDIA_GERAL,645.0,354.856078,368.266348,0.000000,60.950000,231.130000,534.880000,1.908100e+03
INCID_0A10,645.0,233.029132,256.527105,0.000000,35.190000,143.300000,345.270000,1.604940e+03
INCID_60MAIS,645.0,435.785721,483.154753,0.000000,53.040000,255.590000,662.980000,2.308320e+03
PROP_CASOS_0A10,638.0,0.093100,0.054413,0.000000,0.064500,0.088050,0.118050,5.000000e-01
PROP_CASOS_60MAIS,638.0,0.196657,0.087343,0.000000,0.148025,0.199600,0.249850,5.143000e-01
TAXA_MG_100MIL,645.0,12.488651,13.960051,0.000000,1.330000,7.810000,19.330000,8.173000e+01
CLASS_IG,645.0,9.906977,28.891917,0.000000,0.000000,2.000000,7.000000,3.720000e+02
SORO_IG,645.0,18.813953,59.100053,0.000000,1.000000,3.000000,14.000000,9.440000e+02
EVOL_IG,645.0,18.291473,54.742951,0.000000,1.000000,4.000000,12.000000,6.660000e+02
PROP_CLASS_IGN,638.0,0.042547,0.082494,0.000000,0.000000,0.014750,0.044600,1.000000e+00
PROP_SORO_IGN,638.0,0.070271,0.111535,0.000000,0.001925,0.024050,0.092825,1.000000e+00
PROP_EVOL_IGN,638.0,0.080261,0.136025,0.000000,0.004425,0.031100,0.086275,1.000000e+00
BAIXO_N,645.0,0.086822,0.281792,0.000000,0.000000,0.000000,0.000000,1.000000e+00
PROP_CASOS_MG_10,589.0,19.168421,19.161881,0.000000,4.000000,15.900000,27.200000,1.000000e+02
PROP_CASOS_MG_11A59,638.0,3.782602,7.050715,0.000000,0.400000,1.800000,3.800000,5.000000e+01
PROP_CASOS_MG_60,603.0,3.177280,9.885206,0.000000,0.000000,0.000000,2.600000,1.000000e+02

In [129]:
# Proporção de MG por faixa etaria por Região

temporaria = (df.groupby('REGIAO')
 .agg(
     MG_10 = ('MG_10', 'sum'),
     MG_11A59 = ('MG_11A59', 'sum'),
     MG_60 = ('MG_60', 'sum'),
     TOTAL_10A = ('TOTAL_10A', 'sum'),
     TOTAL_11A59 = ('TOTAL_11A59', 'sum'),
     TOTAL_60 = ('TOTAL_60', 'sum')
).assign(
    PROP_CASOS_MG_10 = lambda x: ((x['MG_10'] / x['TOTAL_10A']) * 100).round(1), 
    PROP_CASOS_MG_11A59 = lambda x: ((x['MG_11A59'] / x['TOTAL_11A59']) * 100).round(1),
    PROP_CASOS_MG_60 = lambda x: ((x['MG_60'] / x['TOTAL_60']) * 100).round(1)))

dfReg = dfReg.merge(
    temporaria,
    on='REGIAO',
    how='left'
)

In [130]:
# Describe Regional
dfReg.describe().T

,count,mean,std,min,25%,50%,75%,max
N_PESA,28.0,7.857143e+00,4.187409e+00,1.0,4.750,8.00,9.250,17.0
N_MUNICIPIOS,28.0,2.303571e+01,1.435136e+01,1.0,14.000,23.00,30.750,67.0
POP_REG,28.0,1.633464e+06,2.290537e+06,280506.0,476841.750,921973.00,1655378.000,11950472.0
COB_PESA,28.0,4.402857e+01,2.581894e+01,10.8,28.125,36.05,50.700,100.0
POP_POR_PESA,28.0,6.294898e+05,2.235890e+06,18992.8,76276.775,109318.20,225402.625,11950472.0
TOTAL_MG,28.0,3.210714e+02,3.132338e+02,6.0,62.000,275.00,383.500,1205.0
TOTAL_CASOS,28.0,8.538786e+03,8.785892e+03,44.0,1277.750,6824.50,10861.250,33119.0
PROP_MG,28.0,5.939286e+00,4.351104e+00,2.0,3.350,4.45,6.650,20.5
MG_10,28.0,1.591071e+02,1.751975e+02,1.0,8.750,127.50,193.000,625.0
MG_11A59,28.0,1.273214e+02,1.104942e+02,3.0,46.250,111.00,148.750,446.0
MG_60,28.0,3.235714e+01,3.395336e+01,0.0,5.750,21.00,42.500,133.0
TOTAL_10A,28.0,8.075000e+02,8.314240e+02,4.0,159.750,684.50,916.250,3075.0
TOTAL_11A59,28.0,5.817250e+03,5.848263e+03,33.0,967.250,4677.00,7375.500,21657.0
TOTAL_60,28.0,1.788607e+03,2.040406e+03,6.0,170.500,1443.00,2728.750,8294.0
PROP_CASOS_MG_10,28.0,2.077143e+01,1.168585e+01,4.2,15.150,18.75,22.500,60.0
PROP_CASOS_MG_11A59,28.0,4.446429e+00,4.192010e+00,1.1,1.850,2.60,5.625,20.0
PROP_CASOS_MG_60,28.0,3.821429e+00,4.687758e+00,0.0,1.500,1.80,3.900,21.4

## 3. Integração entre demanda e acesso
* casos e MG por faixas de tempo;
* casos e MG por faixas de distância;
* mapas de demanda versus acessibilidade;
* municípios com alta incidência e maior tempo de acesso.

In [131]:
# Casos por faixas de tempo nos municípios

(df.loc[df['CAT_TEMPO']!='Local',:].groupby('CAT_TEMPO')['TOTAL_CASOS'].sum().reset_index()
 .assign(PROP_CASOS = lambda x: (x['TOTAL_CASOS']/x['TOTAL_CASOS'].sum()*100).round(1)))

   CAT_TEMPO  TOTAL_CASOS  PROP_CASOS
0  31–60 min        22187        31.6
1    >60 min          496         0.7
2    ≤30 min        47605        67.7

In [132]:
# Casos por faixas de tempo nas Regiões
df.loc[df['CAT_TEMPO']!='Local',:].groupby(['REGIAO','CAT_TEMPO'])['TOTAL_CASOS'].sum().reset_index()

                   REGIAO  CAT_TEMPO  TOTAL_CASOS
0               ARACATUBA  31–60 min          726
1               ARACATUBA    ≤30 min         4076
2              ARARAQUARA  31–60 min         1968
3              ARARAQUARA    ≤30 min         1776
4                   ASSIS  31–60 min          567
5                   ASSIS    ≤30 min         1415
6                BARRETOS  31–60 min          568
7                BARRETOS    ≤30 min         1865
8                   BAURU  31–60 min         1546
9                   BAURU    ≤30 min         1644
10               BOTUCATU  31–60 min         1450
11               BOTUCATU    >60 min          117
12               BOTUCATU    ≤30 min          700
13               CAMPINAS  31–60 min         1225
14               CAMPINAS    >60 min           79
15               CAMPINAS    ≤30 min         3739
16                 FRANCA  31–60 min          404
17                 FRANCA    ≤30 min          705
18        FRANCO DA ROCHA  31–60 min          186
19        FRANCO DA ROCHA    ≤30 min          149
20                ITAPEVA  31–60 min            6
21                ITAPEVA    >60 min            2
22                ITAPEVA    ≤30 min            4
23                  JALES  31–60 min         1709
24                  JALES    ≤30 min         3560
25                MARILIA  31–60 min         2078
26                MARILIA    >60 min           58
27                MARILIA    ≤30 min         4078
28        MOGI DAS CRUZES    ≤30 min          179
29                 OSASCO  31–60 min          199
30                 OSASCO    ≤30 min          756
31             PIRACICABA  31–60 min           24
32             PIRACICABA    ≤30 min         2409
33    PRESIDENTE PRUDENTE  31–60 min          174
34    PRESIDENTE PRUDENTE    ≤30 min         1638
35   PRESIDENTE VENCESLAU  31–60 min          246
36   PRESIDENTE VENCESLAU    ≤30 min         1641
37         RIBEIRAO PRETO  31–60 min         1132
38         RIBEIRAO PRETO    ≤30 min         4136
39            SANTO ANDRE  31–60 min           15
40            SANTO ANDRE    ≤30 min          178
41                 SANTOS    ≤30 min           10
42  SAO JOAO DA BOA VISTA  31–60 min          721
43  SAO JOAO DA BOA VISTA    ≤30 min         2341
44  SAO JOSE DO RIO PRETO  31–60 min         5903
45  SAO JOSE DO RIO PRETO    >60 min          235
46  SAO JOSE DO RIO PRETO    ≤30 min         7179
47    SAO JOSE DOS CAMPOS    ≤30 min           42
48               SOROCABA  31–60 min         1319
49               SOROCABA    ≤30 min         1871
50                TAUBATE  31–60 min           21
51                TAUBATE    >60 min            5
52                TAUBATE    ≤30 min         1514

## 4. Comparação temporal (confirmar)
* variação 2019 a 2024
* variação na incidência;
* variação na proporção MG;
* mudança na concentração espacial;
* estabilidade ou alteração das faixas de acesso.

In [133]:
print(
    df.columns, '\n',
    dfReg.columns
)

Index(['Unnamed: 0', 'ACESSO_LOCAL', 'MULTIPLO_PESA', 'REGIAO', 'PESA', 'MUNI',
       'OBSERVACOES', 'LAT_MUNI', 'LON_MUNI', 'LAT_PESA', 'LON_PESA',
       'DISTANCIA', 'TEMPO', 'IBGE', 'POP10', 'POP11A59', 'POP60', 'POP_GERAL',
       'TOTAL_CASOS', 'TOTAL_10A', 'TOTAL_11A59', 'TOTAL_60', 'LEVE', 'MG',
       'MG_ORIGINAL', 'LEVE_10', 'MG_10', 'LEVE_11A59', 'MG_11A59', 'LEVE_60',
       'MG_60', 'TOTAL_AMPOLAS', 'N_PESA', 'CAT_TEMPO', 'PROP_POP_0A10',
       'PROP_POP_60MAIS', 'LOG_POP', 'PROP_MG', 'INCID_MEDIA_GERAL',
       'INCID_0A10', 'INCID_60MAIS', 'PROP_CASOS_0A10', 'PROP_CASOS_60MAIS',
       'TAXA_MG_100MIL', 'CLASS_IG', 'SORO_IG', 'EVOL_IG', 'PROP_CLASS_IGN',
       'PROP_SORO_IGN', 'PROP_EVOL_IGN', 'BAIXO_N', 'PROP_CASOS_MG_10',
       'PROP_CASOS_MG_11A59', 'PROP_CASOS_MG_60'],
      dtype='str')
 Index(['REGIAO', 'N_PESA', 'N_MUNICIPIOS', 'POP_REG', 'COB_PESA',
       'POP_POR_PESA', 'TOTAL_MG', 'TOTAL_CASOS', 'PROP_MG', 'MG_10',
       'MG_11A59', 'MG_60', 'TOTAL_10A', 'TOTAL_11A59', 'TOTAL_60',
       'PROP_CASOS_MG_10', 'PROP_CASOS_MG_11A59', 'PROP_CASOS_MG_60'],
      dtype='str')