In [1]:
import pandas as pd
import openpyxl
from unidecode import unidecode

In [2]:
df1 = pd.read_excel('Dados-iniciais/Referencia-pesa-municipio-v4.xlsx')
df2 = pd.read_excel('Dados-iniciais/Pesa-enderecos-ms-v3.xlsx')

In [3]:
# Normalizando texto df1

colunas_df1 = ['REGIAO', 'PESA_MUNI', 'REFERENCIADO', 'PUBLICO', 'OBSERVACAO', 'muni_limpo']

for i in colunas_df1:
    df1[i] = (
        df1[i]
        .fillna('')              # Substitui valores nulos por texto vazio
        .astype(str)             # Garante que tudo vire texto
        .apply(unidecode)        # Remove acentos
        .str.upper()             # Coloca em caixa alta
    )

In [4]:
# Normalizando texto df2

colunas_df2 = ['PESA_MUNI', 'NOME_PESA', 'ENDERECO','ENDERECO_COMPLETO']

for i in colunas_df2:
    df2[i] = (
        df2[i]
        .fillna('')
        .astype(str)
        .apply(unidecode)
        .str.upper()
    )

In [5]:
#df1.loc[df1['MULTIPLO_PESA']==0]
df1

,MULTIPLO_PESA,REGIAO,PESA_MUNI,REFERENCIADO,PUBLICO,OBSERVACAO,muni_limpo,lat_muni,lon_muni
0,1,SAO PAULO,SAO PAULO,SAO PAULO,TODOS,,SAO PAULO,-23.545308,-46.637769
1,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,DIADEMA,TODOS,,DIADEMA,-23.686643,-46.624693
2,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,MAUA,TODOS,,MAUA,-23.666953,-46.461692
3,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,RIO GRANDE DA SERRA,TODOS,,RIO GRANDE DA SERRA,-23.744190,-46.392475
4,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,SAO CAETANO DO SUL,TODOS,,SAO CAETANO DO SUL,-23.619592,-46.568832
...,...,...,...,...,...,...,...,...,...
676,1,TAUBATE,TAUBATE,TREMEMBE,TODOS,,TREMEMBE,-22.964176,-45.548955
677,1,TAUBATE,TAUBATE,REDENCAO DA SERRA,TODOS,,REDENCAO DA SERRA,-23.280365,-45.534575
678,1,TAUBATE,TAUBATE,NATIVIDADE DA SERRA,TODOS,,NATIVIDADE DA SERRA,-23.378379,-45.443817
679,0,TAUBATE,CARAGUATATUBA,NATIVIDADE DA SERRA,TODOS,BAIRROS POUSO ALTO E POUSO ALTINO,NATIVIDADE DA SERRA,-23.378379,-45.443817
680,0,TAUBATE,PARAIBUNA,NATIVIDADE DA SERRA,TODOS,BAIRROS POUSO ALTO E POUSO ALTINO,NATIVIDADE DA SERRA,-23.378379,-45.443817

In [ ]:
# Join Pesa + Muni (somente Pesa unico e sem observações)
df3 = df1.loc[(
    (df1['MULTIPLO_PESA']==0) & 
    (df1['PUBLICO']=='TODOS') &
    (df1['OBSERVACAO']=='')
    )].merge(
    right=df2.loc[df2['MULTIPLO_PESA']==0],
    how='left',
    left_on='PESA_MUNI',
    right_on='PESA_MUNI'
)

,MULTIPLO_PESA_x,REGIAO,PESA_MUNI,REFERENCIADO,PUBLICO,OBSERVACAO,muni_limpo,lat_muni,lon_muni,MULTIPLO_PESA_y,NOME_PESA,ENDERECO,N,ENDERECO_COMPLETO,lat_pesa,lon_pesa
0,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,DIADEMA,TODOS,,DIADEMA,-23.686643,-46.624693,0,HOSPITAL E PRONTO SOCORRO CENTRAL,RUA SECONDO MODOLIN,499,"RUA SECONDO MODOLIN, 499, SAO BERNARDO DO CAMP...",-23.713091,-46.557753
1,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,MAUA,TODOS,,MAUA,-23.666953,-46.461692,0,HOSPITAL E PRONTO SOCORRO CENTRAL,RUA SECONDO MODOLIN,499,"RUA SECONDO MODOLIN, 499, SAO BERNARDO DO CAMP...",-23.713091,-46.557753
2,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,RIO GRANDE DA SERRA,TODOS,,RIO GRANDE DA SERRA,-23.744190,-46.392475,0,HOSPITAL E PRONTO SOCORRO CENTRAL,RUA SECONDO MODOLIN,499,"RUA SECONDO MODOLIN, 499, SAO BERNARDO DO CAMP...",-23.713091,-46.557753
3,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,SAO CAETANO DO SUL,TODOS,,SAO CAETANO DO SUL,-23.619592,-46.568832,0,HOSPITAL E PRONTO SOCORRO CENTRAL,RUA SECONDO MODOLIN,499,"RUA SECONDO MODOLIN, 499, SAO BERNARDO DO CAMP...",-23.713091,-46.557753
4,0,SANTO ANDRE,SAO BERNARDO DO CAMPO,RIBEIRAO PIRES E RIO,TODOS,,RIBEIRAO PIRES E RIO,-23.447288,-46.531947,0,HOSPITAL E PRONTO SOCORRO CENTRAL,RUA SECONDO MODOLIN,499,"RUA SECONDO MODOLIN, 499, SAO BERNARDO DO CAMP...",-23.713091,-46.557753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,0,TAUBATE,PINDAMONHANGABA,PINDAMONHANGABA,TODOS,,PINDAMONHANGABA,-22.936400,-45.462260,0,PRONTO SOCORRO MUNICIPAL DE PINDAMONHANGABA,RUA MAJOR JOSE DOS SANTOS MOREIRA,466,"RUA MAJOR JOSE DOS SANTOS MOREIRA, 466, PINDAM...",-22.930775,-45.456179
556,0,TAUBATE,SAO BENTO DO SAPUCAI,SAO BENTO DO SAPUCAI,TODOS,,SAO BENTO DO SAPUCAI,-22.688461,-45.732977,0,PRONTO SOCORRO MUNICIPAL DE SAO BENTO DO SAPUCAI,PRACA GENERAL MARCONDES SALGADO,34,"PRACA GENERAL MARCONDES SALGADO, 34, SAO BENTO...",-22.686760,-45.730598
557,0,TAUBATE,SAO JOSE DO BARREIRO,SAO JOSE DO BARREIRO,TODOS,,SAO JOSE DO BARREIRO,-22.645238,-44.580525,0,UNIDADE MISTA DE SAUDE DR. ACACIO DE SAO JOSE ...,RUA JOSE BENTO TEIXEIRA,204,"RUA JOSE BENTO TEIXEIRA, 204, SAO JOSE DO BARR...",-22.647950,-44.575736
558,0,TAUBATE,SAO JOSE DO BARREIRO,ARAPEI,TODOS,,ARAPEI,-22.673889,-44.447778,0,UNIDADE MISTA DE SAUDE DR. ACACIO DE SAO JOSE ...,RUA JOSE BENTO TEIXEIRA,204,"RUA JOSE BENTO TEIXEIRA, 204, SAO JOSE DO BARR...",-22.647950,-44.575736
559,0,TAUBATE,SAO LUIS DO PARAITINGA,SAO LUIS DO PARAITINGA,TODOS,,SAO LUIS DO PARAITINGA,-23.222053,-45.310844,0,SANTA CASA DE MISERICORDIA DE SAO LUIS DO PARA...,PRACA CORONEL TEODORO COELHO,48,"PRACA CORONEL TEODORO COELHO, 48, SAO LUIS DO ...",-23.225311,-45.307459

In [10]:
# Join Pesa + Muni Sit. Especiais (Multiplos Pesa e observaçoes)
df4 = df1.loc[(
    (df1['MULTIPLO_PESA']==1) | 
    (df1['OBSERVACAO']!='')
    )].merge(
    right=df2.loc[df2['MULTIPLO_PESA']==1],
    how='left',
    left_on='PESA_MUNI',
    right_on='PESA_MUNI'
)
df4

,MULTIPLO_PESA_x,REGIAO,PESA_MUNI,REFERENCIADO,PUBLICO,OBSERVACAO,muni_limpo,lat_muni,lon_muni,MULTIPLO_PESA_y,NOME_PESA,ENDERECO,N,ENDERECO_COMPLETO,lat_pesa,lon_pesa
0,1,SAO PAULO,SAO PAULO,SAO PAULO,TODOS,,SAO PAULO,-23.545308,-46.637769,1.0,HOSPITAL GERAL DO GRAJAU PROF. LIBER JOHN ALPH...,RUA FRANCISCO OCTAVIO PACCA,180,"RUA FRANCISCO OCTAVIO PACCA, 180, SAO PAULO, S...",-23.729026,-46.690845
1,1,SAO PAULO,SAO PAULO,SAO PAULO,TODOS,,SAO PAULO,-23.545308,-46.637769,1.0,HOSPITAL KATIA DE SOUZA RODRIGUES TAIPAS,AVENIDA ELISIO TEIXEIRA LEITE,6999,"AVENIDA ELISIO TEIXEIRA LEITE, 6999, SAO PAULO...",-23.443700,-46.717751
2,1,SAO PAULO,SAO PAULO,SAO PAULO,TODOS,,SAO PAULO,-23.545308,-46.637769,1.0,HOSPITAL MUNICIPAL DE PARELHEIROS,RUA EUZEBIO COGHI,841,"RUA EUZEBIO COGHI, 841, SAO PAULO, SP, BRASIL",-23.824773,-46.726643
3,1,SAO PAULO,SAO PAULO,SAO PAULO,TODOS,,SAO PAULO,-23.545308,-46.637769,1.0,HOSPITAL MUNICIPAL DR. CARMINO CARICCHIO,AVENIDA CELSO GARCIA,4815,"AVENIDA CELSO GARCIA, 4815, SAO PAULO, SP, BRASIL",-23.532950,-46.566441
4,1,SAO PAULO,SAO PAULO,SAO PAULO,TODOS,,SAO PAULO,-23.545308,-46.637769,1.0,HOSPITAL MUNICIPAL TIDE SETUBAL,R. DR. JOSE GUILHERME EIRAS,123,"R. DR. JOSE GUILHERME EIRAS, 123, SAO PAULO, S...",-23.497318,-46.439865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,1,TAUBATE,TAUBATE,REDENCAO DA SERRA,TODOS,,REDENCAO DA SERRA,-23.280365,-45.534575,1.0,UPA CENTRAL,RUA BENEDITO CURSINO DOS SANTOS,101,"RUA BENEDITO CURSINO DOS SANTOS, 101, TAUBATE,...",-23.030060,-45.567323
245,1,TAUBATE,TAUBATE,NATIVIDADE DA SERRA,TODOS,,NATIVIDADE DA SERRA,-23.378379,-45.443817,1.0,UNIDADE DE PRONTO SOCORRO INFANTIL. HOSPITAL M...,AVENIDA GRANADEIRO GUIMARAES,270,"AVENIDA GRANADEIRO GUIMARAES, 270, TAUBATE, SP...",-23.021448,-45.556739
246,1,TAUBATE,TAUBATE,NATIVIDADE DA SERRA,TODOS,,NATIVIDADE DA SERRA,-23.378379,-45.443817,1.0,UPA CENTRAL,RUA BENEDITO CURSINO DOS SANTOS,101,"RUA BENEDITO CURSINO DOS SANTOS, 101, TAUBATE,...",-23.030060,-45.567323
247,0,TAUBATE,CARAGUATATUBA,NATIVIDADE DA SERRA,TODOS,BAIRROS POUSO ALTO E POUSO ALTINO,NATIVIDADE DA SERRA,-23.378379,-45.443817,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,0,TAUBATE,PARAIBUNA,NATIVIDADE DA SERRA,TODOS,BAIRROS POUSO ALTO E POUSO ALTINO,NATIVIDADE DA SERRA,-23.378379,-45.443817,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Salvar df3 e df4
df3.to_excel('Dados-iniciais/juntos_unico_pesa.xlsx')
df4.to_excel('Dados-iniciais/juntos_multi_pesa.xlsx')